import type { Metadata } from 'next';
import { site } from './site';

// One builder for every page's metadata, because the alternative had already
// gone wrong.
//
// The root layout used to set `alternates: { canonical: '/' }`, and no page
// overrode it. Next.js inherits root metadata, so every page on the site —
// projects, writing, store, about, every article — declared itself a duplicate
// of the homepage. That is an instruction to Google to index the homepage and
// drop the rest, and a site-restricted search for masterroachi.com returned
// nothing at all, which is exactly what it looks like when that happens.
//
// The Open Graph block had the same fault and was less visible: og:url,
// og:title and og:description were the homepage's on every page, so sharing
// any page anywhere showed the homepage.
//
// So nothing here defaults to a path. `pageMeta` takes the path it is for and
// builds the canonical, og:url and og:title from it, and every page calls it.

export interface PageMetaInput {
  /** Absolute, with the leading and trailing slash — '/store/', '/'. */
  path: string;
  /** The page's own title, without the site name; omit for the homepage. */
  title?: string;
  description: string;
  /** Overrides the default social image for this page. */
  image?: string;
  /**
   * The size of `image`, when it is actually known.
   *
   * This used to be hardcoded to 1200x630 for whatever image it was handed,
   * which was true only of the default card. A post cover is 1440x465 and a
   * product mockup was 567x765, both announced as 1200x630 — and a crawler
   * told the wrong aspect ratio crops the picture to match. Omitted rather
   * than guessed: the tags are optional, and no answer beats a wrong one.
   */
  imageSize?: { width: number; height: number };
  /** What the image shows. Defaults to the site name, which is rarely right. */
  imageAlt?: string;
  /** Articles and project pages, which are not 'website'. */
  type?: 'website' | 'article';
  /** Keeps a draft out of the index while still giving it a real URL. */
  noIndex?: boolean;
}

/** The share image every page falls back to. Generated by scripts/og.mjs. */
export const DEFAULT_OG_IMAGE = '/og.png';

/** The default card's real dimensions, set by scripts/og.mjs. */
const DEFAULT_OG_SIZE = { width: 1200, height: 630 };

export function pageMeta({
  path,
  title,
  description,
  image = DEFAULT_OG_IMAGE,
  imageSize,
  imageAlt,
  type = 'website',
  noIndex,
}: PageMetaInput): Metadata {
  // og:title carries the full title, since it is read on its own in a card
  // with no site chrome around it. The <title> tag keeps the template.
  const fullTitle = title ? `${title} — ${site.name}` : `${site.name} — ${site.tagline}`;
  const url = `${site.url}${path}`;
  // Only the default card's size is known here; anything else has to say so.
  const size = image === DEFAULT_OG_IMAGE ? DEFAULT_OG_SIZE : imageSize;

  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type,
      siteName: site.name,
      title: fullTitle,
      description,
      url,
      locale: 'en_ZA',
      images: [{ url: image, ...(size ?? {}), alt: imageAlt ?? site.name }],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [image],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}
