// Generates lib/toolIcons.ts from simple-icons.
//
//   node scripts/tool-icons.mjs
//
// simple-icons is a devDependency and stays there: importing it at runtime
// would ship 3,457 icons to reach the handful this site uses. The generated
// file holds only those, and is committed.
//
// Brand hexes are authored for light backgrounds. Anything too dark to see on
// this site's near-black is flipped to white, which is how those brands
// present themselves on dark ground anyway.
import fs from 'node:fs';
import * as si from 'simple-icons';

const TOOLS = [
  ['typescript', 'TypeScript'],
  ['javascript', 'JavaScript'],
  ['react', 'React'],
  ['nextdotjs', 'Next.js'],
  ['vuedotjs', 'Vue'],
  ['nuxt', 'Nuxt'],
  ['godotengine', 'Godot'],
  ['python', 'Python'],
  ['html5', 'HTML'],
  ['css', 'CSS'],
  ['claude', 'Claude'],
  ['cursor', 'Cursor'],
];

// LinkedIn is deliberately absent: simple-icons removed it after LinkedIn
// enforced their trademark, and redrawing the mark they objected to would be
// doing knowingly what the removal was about. It renders as a wordmark.
const SOCIALS = [
  ['github', 'GitHub'],
  ['facebook', 'Facebook'],
  ['instagram', 'Instagram'],
  ['youtube', 'YouTube'],
];

/**
 * Whether a brand colour is too close to black to read on this ground.
 *
 * Luminance alone is not enough: pure red scores 0.21 and would be flipped to
 * white despite being perfectly visible. A colour only needs replacing when it
 * is both dark AND close to greyscale — which is what an almost-black brand
 * mark actually is.
 */
function needsLightening(hex) {
  const n = parseInt(hex, 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  const luminance = (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
  const max = Math.max(r, g, b);
  const saturation = max === 0 ? 0 : (max - Math.min(r, g, b)) / max;
  return luminance < 0.22 && saturation < 0.25;
}

function lookup(slug) {
  const key = 'si' + slug.charAt(0).toUpperCase() + slug.slice(1);
  const icon = si[key];
  if (!icon) throw new Error(`simple-icons has no "${slug}"`);
  return icon;
}

function toolRow([slug, label]) {
  const icon = lookup(slug);
  const color = needsLightening(icon.hex) ? 'FFFFFF' : icon.hex;
  const lines = [
    '  {',
    `    label: ${JSON.stringify(label)},`,
    `    color: '#${color}',`,
    `    path: ${JSON.stringify(icon.path)},`,
    '  },',
  ];
  return lines.join('\n');
}

function socialRow([slug, label]) {
  const icon = lookup(slug);
  const color = needsLightening(icon.hex) ? 'FFFFFF' : icon.hex;
  const lines = [
    '  {',
    `    key: ${JSON.stringify(slug)},`,
    `    label: ${JSON.stringify(label)},`,
    `    color: '#${color}',`,
    `    path: ${JSON.stringify(icon.path)},`,
    '  },',
  ];
  return lines.join('\n');
}

const out = [
  '// GENERATED by scripts/tool-icons.mjs — do not edit by hand.',
  '//',
  '// Brand marks from simple-icons, reduced to the ones this site uses.',
  '// Colours too dark to read on a near-black ground are flipped to white.',
  '',
  'export interface ToolIcon {',
  '  label: string;',
  '  color: string;',
  '  /** SVG path data, on a 24x24 viewBox. */',
  '  path: string;',
  '}',
  '',
  'export const TOOL_ICONS: ToolIcon[] = [',
  TOOLS.map(toolRow).join('\n'),
  '];',
  '',
  '/** Tools with no brand mark in simple-icons; rendered as a wordmark. */',
  "export const TOOL_WORDMARKS: string[] = ['Codex'];",
  '',
  'export interface SocialIcon extends ToolIcon {',
  '  key: string;',
  '}',
  '',
  'export const SOCIAL_ICONS: SocialIcon[] = [',
  SOCIALS.map(socialRow).join('\n'),
  '];',
  '',
].join('\n');

fs.writeFileSync('lib/toolIcons.ts', out);
console.log(
  `wrote lib/toolIcons.ts — ${TOOLS.length} tools, ${SOCIALS.length} socials`,
);
