// Generates lib/toolIcons.ts from simple-icons.
//
//   node scripts/tool-icons.mjs
//
// simple-icons is a devDependency and stays there: importing it at runtime
// would ship 3,457 icons to reach the dozen this site uses. The generated file
// holds only those, and is committed.
//
// Brand hexes are authored for light backgrounds. Anything too dark to see on
// this site's near-black is flipped to white, which is how those brands
// present themselves on dark ground anyway.
import fs from 'node:fs';
import * as si from 'simple-icons';

const TOOLS = [
  ['typescript', 'TypeScript'],
  ['javascript', 'JavaScript'],
  ['react', 'React'],
  ['nextdotjs', 'Next.js'],
  ['vuedotjs', 'Vue'],
  ['nuxt', 'Nuxt'],
  ['godotengine', 'Godot'],
  ['html5', 'HTML'],
  ['css', 'CSS'],
  ['claude', 'Claude'],
  ['cursor', 'Cursor'],
];

/** Perceived lightness of a hex, 0–1. */
function lightness(hex) {
  const n = parseInt(hex, 16);
  const r = (n >> 16) & 255;
  const g = (n >> 8) & 255;
  const b = n & 255;
  return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
}

const rows = TOOLS.map(([slug, label]) => {
  const key = 'si' + slug.charAt(0).toUpperCase() + slug.slice(1);
  const icon = si[key];
  if (!icon) throw new Error(`simple-icons has no "${slug}"`);
  const color = lightness(icon.hex) < 0.22 ? 'FFFFFF' : icon.hex;
  return `  {
    label: ${JSON.stringify(label)},
    color: '#${color}',
    path: ${JSON.stringify(icon.path)},
  },`;
}).join('\n');

const out = `// GENERATED by scripts/tool-icons.mjs — do not edit by hand.
//
// Brand marks from simple-icons, reduced to the ones this site uses. Colours
// too dark to read on a near-black ground are flipped to white.

export interface ToolIcon {
  label: string;
  color: string;
  /** SVG path data, on a 24x24 viewBox. */
  path: string;
}

export const TOOL_ICONS: ToolIcon[] = [
${rows}
];

/** Tools with no brand mark in simple-icons; rendered as a wordmark instead. */
export const TOOL_WORDMARKS: string[] = ['Codex'];
`;

fs.writeFileSync('lib/toolIcons.ts', out);
console.log(`wrote lib/toolIcons.ts with ${TOOLS.length} icons`);
